name: Loadtest

on: 
  push:
    branches:
      - master

jobs:

  loadtest:
    name: k6 test run 
    runs-on: ubuntu-latest
  
    steps:

    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Run tests
      uses: k6io/action@v0.1
      with:
        filename: sushi_test.js
        flags: --out influxdb=http://185.177.94.173:8086/myk6db